spring:
  application:
    name: resource
  security:
    oauth2:
      resourceserver:
        jwt: # Placeholder Provider
          issuer-uri: http://localhost:8082
server:
  port: 8081

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka